package com.limitlessmobil.ivendgateway.util;

import java.io.UnsupportedEncodingException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;


public class Test {

	public static String sha512(String input) throws NoSuchAlgorithmException, UnsupportedEncodingException {
	    MessageDigest md5 = MessageDigest.getInstance("SHA-512");
	    byte[] digest = md5.digest(input.getBytes("UTF-8"));
	    StringBuilder sb = new StringBuilder();
	    for (int i = 0; i < digest.length; ++i) {
	        sb.append(Integer.toHexString((digest[i] & 0xFF) | 0x100).substring(1, 3));
	    }
	    return sb.toString();
	}
  
    // Driver code 
    public static void main(String args[]) throws NoSuchAlgorithmException, UnsupportedEncodingException 
    { 
  
        System.out.println("HashCode Generated by SHA-512 for: "); 
                     //2f8SnB|generate_dynamic_bharat_qr|{"transactionId":"zcjS1hQ1iG","transactionAmount":"1.0","outputType":"string"}|LJR1BcnK
        String s1 = "2f8SnB|generate_dynamic_bharat_qr|{\"transactionId\":\"zcjS1hQ1iG\",\"transactionAmount\":\"1.0\",\"outputType\":\"string\"}|LJR1BcnK";
        //String s1 = "5iHUyy|check_bqr_txn_status|{\"transactionId\":\"12345\"}|ozyEFwfA"; 
        System.out.println(s1);
        System.out.println("s1: " + sha512(s1)); 
  
        String s2 = "hello world"; 
        System.out.println("" + s2 + " : " + sha512(s2)); 
        
        String str = "Ram Narayan";
        String s = str.replace("Ram", "Roy");
        System.out.println(s);
    }
}
